<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="042d8024-6b4b-4434-8e77-bf065362c27d" name="Javi@JAVI-PC 2010-09-19 18:29:42" runUser="Javi-PC\Javi" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="da34d0b4-0511-46eb-bb91-669de211e68e">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment userDeploymentRoot="C:\Code\WcfHttpAuth\TestResults" useDefaultDeploymentRoot="false" enabled="false" runDeploymentRoot="Javi_JAVI-PC 2010-09-19 18_29_42">
      <DeploymentItem filename="C:\Code\WcfHttpAuth\WcfHttpAuth\bin\Debug\WcfHttpAuth.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2010-09-19T18:29:42.3467712+02:00" queuing="2010-09-19T18:29:42.5097805+02:00" start="2010-09-19T18:29:42.5537830+02:00" finish="2010-09-19T18:31:51.1261369+02:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="Given_credentials_are_valid_then_should_return_200" storage="c:\code\wcfhttpauth\wcfhttpauth.integrationtests\bin\debug\wcfhttpauth.integrationtests.dll" id="5d656e4d-d5f4-b90e-79a7-216a440af9f0">
      <Execution id="c38dc5d6-e34d-471c-a0cc-a91ed4d05d63" />
      <TestMethod codeBase="C:/Code/WcfHttpAuth/WcfHttpAuth.IntegrationTests/bin/Debug/WcfHttpAuth.IntegrationTests.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="WcfHttpAuth.IntegrationTests.When_calling_a_digest_auth_service, WcfHttpAuth.IntegrationTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="Given_credentials_are_valid_then_should_return_200" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="5d656e4d-d5f4-b90e-79a7-216a440af9f0" executionId="c38dc5d6-e34d-471c-a0cc-a91ed4d05d63" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="c38dc5d6-e34d-471c-a0cc-a91ed4d05d63" testId="5d656e4d-d5f4-b90e-79a7-216a440af9f0" testName="Given_credentials_are_valid_then_should_return_200" computerName="JAVI-PC" duration="00:02:08.1534985" startTime="2010-09-19T18:29:42.5637836+02:00" endTime="2010-09-19T18:31:51.0331316+02:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="c38dc5d6-e34d-471c-a0cc-a91ed4d05d63">
      <Output>
        <ErrorInfo>
          <Message>Test method WcfHttpAuth.IntegrationTests.When_calling_a_digest_auth_service.Given_credentials_are_valid_then_should_return_200 threw exception: 
System.Net.WebException: The remote server returned an error: (401) Unauthorized.</Message>
          <StackTrace>    at System.Net.HttpWebRequest.GetResponse()
   at WcfHttpAuth.Digest.DigestSession.ExecuteRequest(WebRequest request) in C:\Code\WcfHttpAuth\WcfHttpAuth\Digest\DigestSession.cs:line 74
   at WcfHttpAuth.Digest.DigestSession.ExecuteRequest() in C:\Code\WcfHttpAuth\WcfHttpAuth\Digest\DigestSession.cs:line 55
   at WcfHttpAuth.IntegrationTests.When_calling_a_digest_auth_service.Given_credentials_are_valid_then_should_return_200() in C:\Code\WcfHttpAuth\WcfHttpAuth.IntegrationTests\When_calling_a_digest_auth_service.cs:line 35
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>